baseURL = '/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'

title = 'Verilog Note'
theme = 'learn'
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/TZ-Verilog/TZ-Verilog.github.io/edit/main/content/"
  description = "My Verilog Learning Note"
  author = "Todd Zhou"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  themeVariant = "red"
  titleSeparator = " | "

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.zh]
title = "我的Verilog学习笔记"
weight = 3
languageName = "简体中文"
landingPageURL = "/zh"
landingPageName = "<i class='fas fa-home'></i> 家"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 展示区"
url = "/showcase"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文档"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
url = "/credits"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
        mathjax = true